### PR TITLE
Updated admin records in Luxembourg

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/1948.

This PR will update WOF's admin records in Luxembourg using a new public domain dataset provided by Luxembourg's Administration du cadastre et de la topographie.

To do:

- [x] Merge source file in `whosonfirst-sources` repo (*)
- [x] Cessation date for existing regions
- [x] Import new regions
- [x] Update localadmin placetype
- [x] Update locality placetype
- [x] QA neighbourhood placetype
- [x] Verify name and language properties on all records in this repo
- [x] Validate
- [x] PIP

### CODE REVIEW

**Comment by stepps00** [comment]
Commit Notes

523833e: Adds a cessation date to existing regions, flags them as 'not current'
c764d1c: Adds twelve new region records, which represent the cantons of Luxembourg
6120c17: Updates existing WOF localadmin records and adds new localadmin from the `lu-act` source file

**Comment by stepps00** [comment]
@nvkelso this PR is ready for review and PIP work.

This PR updates all placetypes, updating the regions with new divisions and coterminous localadmin/locality records. This will require PIP work, which I'll add once we confirm these changes look good.

**Comment by stepps00** [comment]
Also, this [issue](https://github.com/whosonfirst/whosonfirst-sources/issues/185) includes info on the source for this data.

**Comment by nvkelso** [comment]
@stepps00 let's look at these changes in QGIS this week, please. I'm able to slowly go thru the PR but lots of big geom changes make it not the best venue.

**Comment by stepps00** [comment]
The changes here match expectations for Luxembourg, so the next step is to PIP this features to update hierarchies. I'll start this step soon, and should have this PR ready to merge by early next week.

**Review by nvkelso — APPROVED** [review]
We reviewed in QGIS and looks good, with spot checks in the diff here.

**Comment by stepps00** [comment]
The most recent commit includes all PIP work for this branch. I'll QA this full changeset a bit, then merge if everything looks good.

**Pull request merged**
